version: "3.8"
services:
  mongo:
    image: mongo:6
    container_name: financeai-mongo
    restart: unless-stopped
    ports: ["27017:27017"]
    volumes:
      - mongo-data:/data/db

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: financeai-mssql
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports: ["1433:1433"]

  transactions:
    build: ./services/transactions-service
    container_name: transactions-service
    environment:
      - MONGO_URI=mongodb://mongo:27017/financeai_transactions
      - INTERNAL_SECRET=change-me-in-prod
    ports: ["4100:4100"]
    depends_on: ["mongo"]

  analytics:
    build: ./services/analytics-service
    container_name: analytics-service
    environment:
      - AZURE_SQL_SERVER=mssql
      - AZURE_SQL_DATABASE=financeai_analytics
      - AZURE_SQL_USER=sa
      - AZURE_SQL_PASSWORD=Your_password123
    ports: ["4200:4200"]
    depends_on: ["mssql"]

  bff:
    build: ./bff
    container_name: financeai-bff
    environment:
      - TRANSACTIONS_SERVICE_URL=http://transactions:4100
      - ANALYTICS_SERVICE_URL=http://analytics:4200
      - FUNCTION_TRIGGER_URL=http://functionsmock:4300
      - MOCK_AUTH=true
    ports: ["4000:4000"]
    depends_on: ["transactions","analytics"]

  functionsmock:
    image: node:20
    container_name: functionsmock
    working_dir: /app
    command: ["node","/app/mock-functions-server.js"]
    volumes:
      - ./functions:/app
    ports: ["4300:4300"]

  mfe:
    build: ./mfe
    container_name: financeai-mfe
    ports: ["3000:3000"]
    environment:
      - VITE_BFF_URL=http://localhost:4000

volumes:
  mongo-data:
